# Generated by Django 5.0.6 on 2024-06-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_firstname_alter_profile_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
