# Generated by Django 5.0.6 on 2024-06-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(default='about4.jpg', null=True, upload_to='profile_images'),
        ),
    ]
