# Generated by Django 5.0.6 on 2024-06-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(default='login_295128.png', null=True, upload_to='profile_images'),
        ),
    ]
