# Generated by Django 5.0.6 on 2024-06-24 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthname', models.CharField(max_length=300)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.contribution')),
            ],
        ),
    ]
