# Generated by Django 5.0.6 on 2024-06-24 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.contribution'),
        ),
    ]
