# Generated by Django 5.0.6 on 2024-06-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_month_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='confirmation',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
