# Generated by Django 5.0.6 on 2024-06-24 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
