# Generated by Django 5.0.6 on 2024-06-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
