# Generated by Django 5.0.6 on 2024-06-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productdescription',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
