# Generated by Django 4.2.4 on 2024-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_product_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='confirmation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
