# Generated by Django 4.2.4 on 2024-07-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_confirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
