# Generated by Django 4.2.4 on 2024-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_month_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contributionimage',
            field=models.ImageField(blank=True, null=True, upload_to='contribution_images'),
        ),
    ]
