# Generated by Django 4.2.4 on 2024-07-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_contribution_contributionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyimage', models.ImageField(upload_to='body_image')),
                ('logoimage', models.ImageField(upload_to='logo_image')),
            ],
        ),
    ]
