# Generated by Django 5.0.6 on 2024-07-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_theimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='theimages',
            name='pimage',
            field=models.ImageField(default='media/login_295128.png', upload_to=''),
        ),
    ]
