# Generated by Django 5.0.6 on 2024-07-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_theimages_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
