# Generated by Django 5.0.6 on 2024-07-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_contribution_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theimages',
            name='bodyimage',
            field=models.ImageField(blank=True, null=True, upload_to='body_image'),
        ),
        migrations.AlterField(
            model_name='theimages',
            name='logoimage',
            field=models.ImageField(blank=True, null=True, upload_to='logo_image'),
        ),
        migrations.AlterField(
            model_name='theimages',
            name='pimage',
            field=models.ImageField(blank=True, default='media/login_295128.png', null=True, upload_to=''),
        ),
    ]
