# Generated by Django 5.0.6 on 2024-11-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_theimages_bodyimage_alter_theimages_logoimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(blank=True, default='login_295128.png', null=True, upload_to='profile_images'),
        ),
    ]
