# Generated by Django 5.0.6 on 2024-11-27 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_profile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmpayment',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.month'),
        ),
    ]
