# Generated by Django 5.0.6 on 2024-11-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_confirmpayment_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmpayment',
            name='month',
        ),
        migrations.AddField(
            model_name='contribution',
            name='months',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20, null=True),
        ),
    ]
