# Generated by Django 5.0.6 on 2024-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_confirmpayment_month_contribution_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('phonenumber', models.IntegerField(blank=True, max_length=1000, null=True)),
                ('foodname', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
