# Generated by Django 5.0.6 on 2024-11-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_ordermade_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermade',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
