# Generated by Django 5.0.6 on 2024-11-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_ordermade_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermade',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
