# Generated by Django 5.0.6 on 2024-11-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_ordermade_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutimage', models.ImageField(blank=True, null=True, upload_to='about_images')),
            ],
        ),
        migrations.CreateModel(
            name='ContactImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutimage', models.ImageField(blank=True, null=True, upload_to='contact_images')),
            ],
        ),
    ]
